spring:
  data:
    mongodb:
      host: 127.0.0.1
      port:
      database:

  main:
    allow-bean-definition-overriding: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2
